version: 0.2
env:
  secrets-manager:
    LOGIN: sonartest-scm:sonartoken
    HOST: sonartest-scm:HOST
    Organization: sonartest-scm:Organization
    Project: sonartest-scm:Project
phases:
 install:
   runtime-versions:
     java: corretto17
  pre_build:
    commands:
      - apt-get update
      - pip3 install --upgrade awscli
      - apt-get install -y jq
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      - tar xzf apache-maven-3.9.11-bin.tar.gz
      - ln -s apache-maven-3.9.11 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.1.0.1829-linux.zip
      - unzip ./sonar-scanner-cli-4.1.0.1829-linux.zip
      - export PATH=$PATH:/sonar-scanner-4.1.0.1829-linux/bin/
 build:
   commands:
     - echo "Running SonarQube analysis..."
     - mvn clean verify sonar:sonar \
         -Dsonar.projectKey=$SONAR_PROJECT_KEY \
         -Dsonar.host.url=$SONAR_HOST_URL \
         -Dsonar.login=$SONARQUBE_TOKEN
 post_build:
   commands:
     - echo "Checking SonarQube Quality Gate..."
     - status=$(curl -s -u $SONARQUBE_TOKEN: \
       "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" \
       | jq -r '.projectStatus.status')
     - if [ "$status" != "OK" ]; then
         echo "SonarQube Quality Gate failed!";
         exit 1;
       else
         echo "SonarQube Quality Gate passed!";
       fi
artifacts:
 files:
   - target/*.jar
